version: '2'

networks:
  studentTaskChecker:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.22/16
          gateway: 172.18.0.1

services:
  zipkin-storage:
    image: openzipkin/zipkin-mysql
    container_name: mysql
    networks:
      - studentTaskChecker
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      - studentTaskChecker
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
    ports:
      - "9411"
    depends_on:
      - zipkin-storage

  config-service:
    container_name: config-service
    build:
      context: ./config-service
      dockerfile: dockerfile
    image: config-service:latest
    networks:
      - studentTaskChecker
    ports:
      - "8888"

  discovery-service-peer1:
    container_name: discovery-service-peer1
    build:
      context: ./discovery-service
      dockerfile: dockerfile-p1
    image: discovery-service-peer1:latest
    networks:
      - studentTaskChecker
    ports:
      - "8761"
    depends_on:
      - config-service

  discovery-service-peer2:
    container_name: discovery-service-peer2
    build:
      context: ./discovery-service
      dockerfile: dockerfile-p2
    image: discovery-service-peer2:latest
    networks:
      - studentTaskChecker
    ports:
      - "8761"
    depends_on:
      - config-service

  email-service:
    container_name: email-service
    build:
      context: ./email-service
      dockerfile: dockerfile
    image: email-service:latest
    networks:
      - studentTaskChecker
    ports:
      - "8080"
    depends_on:
      - config-service
      - discovery-service-peer1
      - discovery-service-peer2

  course-service:
    container_name: course-service
    build:
      context: ./course-service
      dockerfile: dockerfile
    image: course-service:latest
    networks:
      - studentTaskChecker
    ports:
      - "8081"
    depends_on:
      - config-service
      - discovery-service-peer1
      - discovery-service-peer2